---
earliest_version: v1.4.0
release_tag_re: 'v\d\.\d\.\d(rc\d+)?'
sections:
  # The prelude section is implicitly included.
  - [features, New Features]
  - [issues, Known Issues]
  - [upgrade, Upgrade Notes]
  - [deprecations, Deprecation Notes]
  - [fixes, Bug Fixes]
  - [other, Other Notes]
